### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by hyichao** [watsonyanghx/CNN_LSTM_CTC_Tensorflow#2]
Hi,
Is it possible that you provide your data (maybe part of them) for those want to have a try? A link or something. Thanks.

**Comment by watsonyanghx** [comment]
I don't know whether I have the right to make these datasets pullic, so I don't post the address in the README file.

If you want to have a try, the dataset can be downloaded from bellow:

[Training dataset](http://baidudeeplearning.bj.bcebos.com/image_contest_level_1.tar.gz)

[Testing dataset](http://baidudeeplearning.bj.bcebos.com/image_contest_level_1_validate.tar.gz)

**Comment by hyichao** [comment]
@watsonyanghx  Thx.

**Comment by indra215** [comment]
Hi,
But there are no labels for the validation data to compute the accuracy. Can you please tell me where can I find that ? Thanks.

**Comment by dortonway** [comment]
@indra215, look at [helper.py](https://github.com/watsonyanghx/CNN_LSTM_CTC_Tensorflow/blob/master/README.md#run-with-your-own-data).

**Comment by luoqingyu** [comment]
Thank you.

**Comment by najourahal** [comment]
The file 'a.txt' does not exist!!!

**Comment by cherish24** [comment]
Thank for your help

**Comment by cherish24** [comment]
I had met som problem that there are no lables for train and test.Can you provide this for me.thanks!

**Comment by cherish24** [comment]
ok  i  have  found  label.txt

**Comment by CelereionHook** [comment]
Hmmm....I still can not found the labels would u plz to teach me how to find the labels for the dataset?

**Comment by jiangpeng12345** [comment]
> ok i have found label.txt

hi where did you find the label.txt file?

**Comment by CelereionHook** [comment]
i found it in github sooo i need ur help....plz tnx a lot

At 2019-02-15 14:28:35, "jiangpeng12345" <notifications@github.com> wrote:


ok i have found label.txt

hi where did you find the label.txt file?

**Comment by Aditichintamani** [comment]
can i know where to find label.txt . Thank you

**Comment by siddhantkaushal** [comment]
HI,

Can you please let me know that how can I get the labels.txt file.. Thank You :)

**Comment by Doan-Nguyen** [comment]
@siddhantkaushal @Aditichintamani when you down load folder "image_contest_level_1", then labels.txt in folder this.

**Comment by GanggangDong** [comment]
good, have a try

**Comment by wiyr** [comment]
dataset is not available now, can i still find it ?
